### ISSUE TITLE
nbviewer links to each tutorial

### ISSUE THREAD

**Issue by joyrexus** [mrocklin/pydata-toolz#1]
FWIW, the following links open up your tutorial notebooks in IPython's notebook viewer.  Might be handy for anyone who wants a quick look ... esp if placed in the README.
- [map-filter-reduce-groupby](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/1-map-filter-reduce-groupby.ipynb)
- [composition](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/2-composition.ipynb)
- [curry](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/3-curry.ipynb)
- [wordcount](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/4-wordcount.ipynb)
- [laziness](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/5-laziness.ipynb)
- [genomics](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/6-genomics.ipynb)
- [fib-memoize](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/7-fib-memoize.ipynb)
- [groupby-github](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/mrocklin/pydata-toolz/master/8-groupby-github.ipynb)

Gist version [here](https://gist.github.com/joyrexus/9792547).

**Comment by mrocklin** [comment]
Great idea!  Care to issue a pull request?

**Comment by joyrexus** [comment]
@mrocklin Thanks for merging this in.
